export const issues = [
  {
    id: "1",
    title: "Deep Pothole on Main road",
    location: "Kalanki road, Kathmandu",
    status: "Pending",
    category: "Potholes",
    upvotes: 33,
    date: "Aug 12, 2026",
    description: "A large pothole has formed on the main road near Kalanki, roughly 2 feet wide. Vehicles are swerving to avoid it, creating a traffic hazard, especially during peak hours and at night.",
    latitude: 27.6939,
    longitude: 85.282,
    image: require("../assets/images/pothhole.jpg"),
  },
  {
    id: "2",
    title: "Cracked Road Near Bus Stop",
    location: "Kalanki road, Kathmandu",
    status: "In Progress",
    category: "Potholes",
    upvotes: 18,
    date: "Aug 20, 2026",
    description: "Multiple cracks have appeared in the road surface near the bus stop, making it uncomfortable and risky for both pedestrians and vehicles.",
    latitude: 27.6942,
    longitude: 85.2815,
    image: require("../assets/images/pothhole.jpg"),
  },
  {
    id: "3",
    title: "Broken Street Light",
    location: "Kalanki road, Kathmandu",
    status: "In Progress",
    category: "Streetlights",
    upvotes: 91,
    date: "Aug 5, 2026",
    description: "The street light at this junction has been broken for over a week, leaving the area dark and unsafe for pedestrians at night.",
    latitude: 27.6945,
    longitude: 85.2836,
    image: require("../assets/images/brokenlight.jpg"),
  },
  {
    id: "4",
    title: "Streetlight Not Working",
    location: "Satdobato, Kathmandu",
    status: "Pending",
    category: "Streetlights",
    upvotes: 27,
    date: "Aug 25, 2026",
    description: "This streetlight has stopped working, reducing visibility along a busy stretch of road used heavily by commuters in the evening.",
    latitude: 27.6688,
    longitude: 85.3247,
    image: require("../assets/images/brokenlight.jpg"),
  },
  {
    id: "5",
    title: "Garbage Management",
    location: "Kalanki road, Kathmandu",
    status: "Resolved",
    category: "Dumping",
    upvotes: 12,
    date: "Jul 30, 2026",
    description: "Uncollected garbage had been piling up at this spot for several days. The municipal cleaning crew has since cleared the area and set up a proper collection schedule.",
    latitude: 27.6928,
    longitude: 85.2808,
    image: require("../assets/images/garbage.jpg"),
  },
  {
    id: "6",
    title: "Illegal Waste Dumping",
    location: "Ring Road, Kathmandu",
    status: "Pending",
    category: "Dumping",
    upvotes: 45,
    date: "Aug 27, 2026",
    description: "Waste is being illegally dumped along the roadside near Ring Road, creating a health hazard and unpleasant smell for nearby residents.",
    latitude: 27.6905,
    longitude: 85.2865,
    image: require("../assets/images/garbage.jpg"),
  },
];

export const statusColors: Record<string, { bg: string; text: string }> = {
  Pending: { bg: "#FDE8E8", text: "#C53030" },
  "In Progress": { bg: "#FEF3C7", text: "#B45309" },
  Resolved: { bg: "#DCFCE7", text: "#15803D" },
};